import type { Metadata } from "next";
import { Press_Start_2P, Quantico } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Navbar } from "@/widgets/navbar/ui/navbar";

const quantico = Quantico({
  variable: "--font-quantico",
  subsets: ["latin"],
  weight: ["400", "700"],
});
const pressStart2P = Press_Start_2P({
  variable: "--font-start-2p",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-black min-h-screen w-screen relative flex flex-col ${pressStart2P.variable} ${quantico.variable} antialiased`}
      >
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
